[package]
name = "dynamo_mapper_macro"
version = "0.1.0"
authors = ["Varkal <moreau.romain83@gmail.com>"]
edition = "2018"

description = "Utility library for dynamo_mapper. Don't use by itself"
license = "MIT"

[lib]
proc-macro = true

[dependencies]
syn = "0.15.34"
quote = "0.6.12"
